apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: bgd
    argo.cntk/instance: bgd
  name: route-bgd
  namespace: bgd
spec:
  host: route-bgd-bgd.apps.ocp-663001ouoh-e67d.cloud.techzone.ibm.com
  port:
    targetPort: 8080
  to:
    kind: Service
    name: bgd
    weight: 100
  wildcardPolicy: None
